In [7]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

idx = np.random.permutation(6)

In [8]:
idx

array([0, 1, 2, 4, 5, 3])

In [10]:
x = x[idx]

In [11]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [ 7,  8],
       [ 9, 10]])

In [14]:
x.dtype

dtype('int32')

In [15]:
from scipy.stats import reciprocal, uniform

In [16]:
a = reciprocal(0.001, 0.1)

In [19]:
c = uniform(1,10)

In [20]:
c

In [25]:
a.pdf(0.001)

217.1472409516259

In [27]:
a.rvs(23)

array([0.00141074, 0.03290122, 0.02664943, 0.02975837, 0.01263899,
       0.08065265, 0.00228964, 0.02749243, 0.00160511, 0.01771106,
       0.00245925, 0.03849171, 0.08241276, 0.01241559, 0.029762  ,
       0.00440965, 0.0331366 , 0.00428467, 0.09611018, 0.02026867,
       0.00155947, 0.00403828, 0.00736601])

In [28]:
c.rvs(10)

array([ 1.83958984,  4.51149491,  4.70396735,  6.62623316,  2.26552567,
        8.51554273,  8.41385996,  3.68721999, 10.8758867 ,  6.03960108])