In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

print(np.dot(arr1,arr2))

[[ 7 10]
 [15 22]]


In [3]:
print(np.poly([-1, 1, 1, 10]))

[  1. -11.   9.  11. -10.]


In [4]:
op = "push 4"
l = op.split(" ")

In [5]:
l

['push', '4']

In [6]:
def superStack(operations):
    superstack = []
    
    for operation in operations:
        ops = operation.split(" ")
        if(ops[0] =="pop"):
            if(len(superstack)<1):
                print("Empyty")
            else:
                superstack.pop()
                if(len(superstack)<1):
                    print("Empyty")
                else:
                    print(superstack[len(superstack)-1])
        if(ops[0]=="push"):
            superstack.append(int(ops[1]))
            print(ops[1])
        if(ops[0]=="inc"):
            for i in range(int(ops[1])):
                superstack[i] = superstack[i]+ int(ops[2])
            print(superstack[len(superstack)-1])
    return superstack;

In [7]:
ls = ["12", "push 4", "pop", "push 3", "push 5","push 2", "inc 3 1", "pop","push 1", "inc 2 2", "push 4","pop", "pop"]

In [8]:
stack = superStack(ls)

4
Empyty
3
5
2
3
6
1
1
4
1
8


In [9]:
print(stack)

[6, 8]


In [10]:
def Substring(string):
    newString = string
    substr = []
    while len(newString)!=1:
        for i in range(1, len(newString)+1):
            if(newString[:i] not in substr):
                substr.append(newString[:i])
      
        newString=newString[1:]
        if(len(newString)==1):
            if(newString[0] not in substr):
                substr.append(newString[0])
    return substr

In [11]:
c = Substring("kincenvizh")

In [12]:
print(len(c))

53


In [13]:
s=Substring("aaaa")

In [14]:
print(len(s))

4


In [15]:
t = [[1,2],[3,4],[5,6]]

In [16]:
import numpy as np

In [17]:
t = np.array(t)

In [18]:
t

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
t[:,1]

array([2, 4, 6])

In [20]:
t[:,0]

array([1, 3, 5])

In [21]:
t[0,:]

array([1, 2])

In [22]:
def calculateProfit(n, earning, cost, e):
	money = 0
	for i in range(n):
		if(i==n-1):
			money += e*earning[i]
			return money
		if(earning[i]>cost[i]):
			money += e*earning[i]
			money = money-e*cost[i]
	return money

n , earning, cost, e = 3, [1,5,5],[2,1,4], 4

money = calculateProfit(n, earning, cost,e)

print(money)

36


In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split